name: ElementalCompanions
version: ${project.version}
main: me.numin.elementalcompanions.ElementalCompanions
api-version: 1.14
softdepend: [ProjectKorra]
authors: [Numin]
description: Companions to follow you, empower bending, and defend you!

commands:
  elementalcompanions:
    usage: /<command>
    description: Base for the command.
  ec:
    usage: /<command>
    description: Base for the command.